name: Verify SQLite Schema

on:
  pull_request:
    branches:
      - main

jobs:
  verify-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SQLite
        run: sudo apt-get install -y sqlite3

      - name: Build Database
        run: |
          DB_FILE=db/my_database.db
          mkdir -p db
          rm -f $DB_FILE
          for f in db/tables/*.sql; do
            sqlite3 $DB_FILE < "$f"
          done