name: Verify SQLite Schema

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verify-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SQLite
        run: sudo apt-get install -y sqlite3

      - name: Test schema
        run: |
          sqlite3 :memory: < db/schema.sql
